package lk.ijse.gdse.HelloShoeShopManagementSystem.dto;

import jakarta.validation.constraints.*;
import lk.ijse.gdse.HelloShoeShopManagementSystem.Enum.Role;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.RequiredArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@RequiredArgsConstructor
public class UserDTO {
    @Null(message = "Id generated by Program")
    private String id;
    @NotNull(message = "Email cannot be null")
    @Email
    private String email;
    @NotNull(message = "Password cannot be null")
    private String password;
    @NotNull(message = "Role cannot be null")
    private Role role;
}
